on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'


jobs:

  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: li1ht2ay-3es/li1re2ro-3an4y@cron
        with:
          token: ${{ secrets.token }}
